# Generated by Django 5.1.4 on 2024-12-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_is_salw_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_salw',
            new_name='is_sale',
        ),
    ]
