# Generated by Django 5.1.4 on 2024-12-31 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('specifications', models.JSONField(default=dict)),
                ('image1', models.ImageField(upload_to='', verbose_name='uploads/product_details/')),
                ('image2', models.ImageField(upload_to='', verbose_name='uploads/product_details/')),
                ('image3', models.ImageField(upload_to='', verbose_name='uploads/product_details/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.customer')),
                ('productDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.product_details')),
            ],
        ),
    ]
