# Generated by Django 5.1.4 on 2025-01-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_customer_user'),
    ]

    operations = [
    ]
